---
# tasks file for neovim
- import_tasks: brew-install.yml
  when: ansible_distribution == 'MacOSX'
- import_tasks: apt-install.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
